# api进程 要跟 srv,  consul通信，但是这个不是 api网关
# 跟 srv, consul 通信依靠 nodePort 就可以了,不用启动时指定
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: micro-xxshop-srv-auth-api 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: micro-xxshop-srv-auth-api-xx
        run: micro-xxshop-srv-auth-api 
    spec:
      containers:
        - name: micro-xxshop-srv-auth-api 
          image: 10.86.20.57:5000/micro-xxshop-srv-auth:v1 
          command: [
            "/xxshop-srv-auth-api",   
            "--registry_address=10.86.20.63:8500",
          ]



