# micro srv 本身不对外服务，也不用被其他的 service或者pod来引用， 所以不用设置 service
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: micro-xxshop-srv-auth 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: micro-xxshop-srv-auth-xx
        run: micro-xxshop-srv-auth 
    spec:
      containers:
        - name: micro-xxshop-srv-auth 
          image: 10.86.20.57:5000/micro-xxshop-srv-auth:v1 
          command: [
            "/xxshop-srv-auth",   
            "--registry_address=10.86.20.63:8500",
          ]



